platform :ios, '8.0'
use_frameworks!

target 'DBMusic' do
  pod 'JVFloatingDrawer', '~> 0.1.0'
  pod 'Alamofire', '2.0.2'
  pod 'SwiftyJSON', '2.3.0'
  pod 'SDWebImage', '3.7.3'
  pod 'KVNProgress', '2.2.1'
  pod 'SVProgressHUD', '1.1.3'
  pod 'ReachabilitySwift', '2.0'
  pod 'AFSoundManager', '1.2.5'
end

target 'DBMusicTests' do

end

